---
name: "Install LLVM and Clang"
description: "Installs LLVM and Clang on CI runners"
inputs:
  version:
    description: "Which version of LLVM to install. E.g '19 or 'clang-19'."
    required: true
runs:
  using: "composite"
  steps:
    - name: Install LLVM and Clang
      shell: bash
      run: |
        LLVM_VERSION=`echo ${{ inputs.version }} | cut -d'-' -f 2`
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh $LLVM_VERSION
        rm llvm.sh
        sudo apt-get install -y clang-tidy-$LLVM_VERSION clang-format-$LLVM_VERSION
